### ISSUE TITLE
Multiple Masters in config?

### ISSUE THREAD

**Issue by sa02** [saltstack/pepper#103]
Is it possible to select from a list of servers in config on startup.

**Comment by gtmanfred** [comment]
This has been added. you can now specify multiple profiles in the config, and you specify which one you want to use 

```
[main]
SALTAPI_URL=https://localhost:8000/
SALTAPI_USER=saltdev
SALTAPI_PASS=saltdev
SALTAPI_EAUTH=pam
[remote]
SALTAPI_URL=https://gtmanfred.com:8000/
SALTAPI_USER=saltdev
SALTAPI_PASS=saltdev
SALTAPI_EAUTH=pam
```

then `pepper -p remote \* test.ping`

Daniel
