### ISSUE TITLE
0.5.3 is no longer on PyPI

### ISSUE THREAD

**Issue by oeuftete** [saltstack/pepper#121]
https://pypi.python.org/simple/salt-pepper/ doesn't show 0.5.3 in the list.

```
$ pip install salt-pepper==0.5.3
Collecting salt-pepper==0.5.3
  Could not find a version that satisfies the requirement salt-pepper==0.5.3 (from versions: 0.2.0, 0.3.0, 0.3.5, 0.3.6, 0.3.7, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.4)
No matching distribution found for salt-pepper==0.5.3
```

Was this intentional because of the problem in #116?  If so, can it please be replaced?  It was still usable, and used.

**Comment by gtmanfred** [comment]
Readded.

**Comment by gtmanfred** [comment]
sorry, but it looks like pypi does not allow me to reupload that.

https://upload.pypi.org/help/#file-name-reuse

I will make a note of that, and in the future not remove them.
