### ISSUE TITLE
Pepper is unhappy when salt returns with list

### ISSUE THREAD

**Issue by aesposito91** [saltstack/pepper#127]
Seems to be related to the return from salt being a list versus a key/value
Same is experienced with manage.up

$ pepper --client runner manage.down -vvv
Use Salt outputters
INFO 2018-03-08 03:09:50,334 pepper: Use Salt outputters
'list' object has no attribute 'items'
Uncaught Pepper error (increase verbosity for the full traceback).
Uncaught traceback:
Traceback (most recent call last):
  File "/apps/pepper/bin/pepper", line 61, in __call__
    for minionid, minionret in ret.items():
AttributeError: 'list' object has no attribute 'items'
DEBUG 2018-03-08 03:09:50,335 pepper: Uncaught traceback:
Traceback (most recent call last):
  File "/apps/pepper/bin/pepper", line 61, in __call__
    for minionid, minionret in ret.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by gtmanfred** [comment]
This is fixed.
