### ISSUE TITLE
Provide an example of ~/.pepperrc

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/pepper#18]
It would be nice to have a documentation (or in the README) that provides an example of .pepperrc 

```
[main]
SALTAPI_URL=https://localhost:8000/
SALTAPI_USER=saltdev
SALTAPI_PASS=saltdev
SALTAPI_EAUTH=pam
```

**Comment by whiteinge** [comment]
Good call! I believe your syntax is indeed correct. Care to submit a pull req?

**Comment by jalons** [comment]
This issue can be closed per https://github.com/saltstack/pepper/pull/20

**Comment by whiteinge** [comment]
Thanks.
