### ISSUE TITLE
Use https by default

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/pepper#21]
I think the code should try https://localhost:8000 by default thus promoting using ssl security by default. 

In my case, after following the instructions to activate salt-api  (with the ultra simple ``salt-call tls.create_self_signed_cert``) when seeing that pepper used http://localhost:8000 I could have chosen to downgrade my salt-api configuration instead of upgrading my configuration of pepper...

**Comment by whiteinge** [comment]
Completely agree! Well said.

This coincides nicely with the last commit in saltstack/salt#20231 that went in this morning.
