### ISSUE TITLE
Using pepper to get list of registered salt-minions ?

### ISSUE THREAD

**Issue by tjyang** [saltstack/pepper#224]
From reading  [REAMED.md](https://github.com/saltstack/pepper/blob/develop/README.rst#pepper) , my understanding salt-key is still not implemented.

I am hoping command like following will works.
```
pepper salt-key -l accepted
```

**Comment by max-arnold** [comment]
Try the key wheel module https://docs.saltproject.io/en/latest/ref/wheel/all/salt.wheel.key.html#salt.wheel.key.list_

**Comment by barneysowood** [comment]
Closing this as Max has answered this.
