### ISSUE TITLE
Add Salt outputters

### ISSUE THREAD

**Issue by whiteinge** [saltstack/pepper#3]
We will need access to Salt's outputters (at least the default one) to complete the illusion. It would be ideal to not have to copy that code into this project. Could it be a build-dep?

**Comment by arthurlogilab** [comment]
I think a build-dep would be ok.

Can salt-api already take an outputter option ?

**Comment by whiteinge** [comment]
If you specify the `Accept` header in your requests salt-api will happily oblige. It would be trivial to add support for Salt's [nested](http://docs.saltstack.com/en/latest/ref/output/all/salt.output.nested.html#module-salt.output.nested) outputter and return everything as a giant string. It's possible that color escape codes would even come through unscathed.

**Comment by arthurlogilab** [comment]
Can you think of a way to pipe the json result to do something like : 

```
pepper 'host' state.highstate | salt-call --output highstate --local something
```

**Comment by arthurlogilab** [comment]
I've failed with 

```
pepper 'host' state.highstate  | salt-call --local --output highstate test.outputter 
```
or
```
salt-call --local --output highstate test.outputter "`pepper 'host' state.highstate `" 
```

**Comment by whiteinge** [comment]
Outputter modules are written to run for each minion return, not on the data as a whole. To do this you'd need to write a small Python wrapper script.

**Comment by arthurlogilab** [comment]
Here is a wrapper script that seems to do the job (so far) : 

```py
import __builtin__
import sys
import json

import salt.config
from salt.output.highstate import output

__opts__ = salt.config.minion_config('/etc/salt/minion')
__opts__['color']=True
__opts__['state_output_diff'] = True
__opts__['state_verbose'] = False
setattr(__builtin__, '__opts__', __opts__)
print output(json.load(sys.stdin))



```

**Comment by arthurlogilab** [comment]
it works with highstate dictionnary data, but if you send it the result of a test.ping execution, it truncates the results. 

I don't think there is a smart way of selecting the right outputter without further context in the results.

**Comment by whiteinge** [comment]
Thanks for posting your wrapper. I'm sure others will find that useful.

You're definitely right about not having enough information to decide which outputter to use. Although that information is in the job cache, most (all?) modules don't expose or display it.

**Comment by whiteinge** [comment]
The [jobs.print_job](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.print_job) runner function will output which outputter to use -- which may be helpful but would still require some indirection (run the job async, get the jid, poll for the jid, pipe the result through your wrapper).

**Comment by bbinet** [comment]
+1, being able to use Salt outputters directly from Pepper would be very useful indeed!

@arthurlogilab: I tried a slightly modified version of your python script (customized for running `jobs.lookup_jid` runner):
``` python
import __builtin__
import subprocess
import sys
import json

import salt.config
from salt.output.highstate import output

__opts__ = salt.config.minion_config('')
__opts__['color']=True
__opts__['state_output_diff'] = True
__opts__['state_verbose'] = False
setattr(__builtin__, '__opts__', __opts__)
#print output(json.load(sys.stdin))
print output(json.loads(subprocess.check_output(
    ['pepper', '--client=runner', 'jobs.lookup_jid', 'jid=%s' % sys.argv[1]])))
```

But for some reason, it does not work and returns:
```
return:
    Data failed to compile:
----------
[...]
```
Any idea why it does not work

**Comment by ghost** [comment]
any update on this issue ?

**Comment by cmclaughlin** [comment]
pepper is really nice... this feature would be icing on the cake!

**Comment by bbinet** [comment]
For those interested, I've created the script https://gist.github.com/bbinet/d87bf2571652e4dec68df6b280b2af9d to format pepper output using salt outputters.
It can both format sync and async jobs, and can be used in the following ways:
```
$ pepper \* state.sls core | pepper_format.py -o highstate
$ pepper --client=local_async \* state.highstate | pepper_format.py
$ pepper_format.py 20170504160400750792
```

```
$ pepper_format.py -h
usage: pepper_format.py [-h] [-o OUTPUTTER] [-v] [-p] [-n] [jid]

Format pepper output using any salt outputter

positional arguments:
  jid                   Optional job id

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUTTER, --outputter OUTPUTTER
                        Outputter to use
  -v, --verbose         Verbose output
  -p, --profiling       Activate profiling
  -n, --no-color        No color in output
```

**Comment by arthurzenika** [comment]
@bbinet nice one ! Thanks a bunch...

**Comment by bbinet** [comment]
Note that I've submitted PR https://github.com/saltstack/salt/pull/41090 to make the profiling option work (it currently raises an exception)

**Comment by cmclaughlin** [comment]
@bbinet thanks!

**Comment by gtmanfred** [comment]
The next version of pepper will use the salt outputters if salt is installed.

**Comment by arthurzenika** [comment]
@gtmanfred glad to hear that... great news!

**Comment by hedrickbt** [comment]
On Ubuntu, if you
"apt install salt-common"

the output modules will be available.  It will also default to the format you expect.

**Comment by lizhixin3016** [comment]
I solved the format problem by "pip/pip3 install salt"
