### ISSUE TITLE
recommend configuration of authorisation of only jobs.lookup_jid for @runner in ACL

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/pepper#32]
If there is a way of restricting on the salt-api, it would be nice to recommend opening only 'jobs.lookup_jid' in '@runner'. I haven't yet found the documentation on how to do this, but if it is not possible I'll go and put an issue on salt.

**Comment by whiteinge** [comment]
This would be a great addition to Salt. Issue here: saltstack/salt#19732
