### ISSUE TITLE
New release on pypi at some point?

### ISSUE THREAD

**Issue by gravyboat** [saltstack/pepper#33]
The last release on pypi was 0.30 (which is not tagged here). Any chance a new tag can be cut to get a newer release out?

**Comment by TheScriptSage** [comment]
We could use this as well, thanks for opening this!

**Comment by whiteinge** [comment]
Looks like I forgot to push that tag. :grimacing: I'll get that and a new release pushed shortly.

**Comment by gravyboat** [comment]
Awesome thanks @whiteinge!

**Comment by TheScriptSage** [comment]
Has this been pushed?

**Comment by whiteinge** [comment]
Pushed 0.3.0 and cut 0.3.5. Release is live here and on PyPI.

**Comment by whiteinge** [comment]
@gravyboat thanks for the bump on this.

**Comment by gravyboat** [comment]
@whiteinge For sure! Thanks for the quick resolution. I'm going to close this out :+1:

**Comment by TheScriptSage** [comment]
Thanks!
