### ISSUE TITLE
Add support for python setup develop

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/pepper#35]
I have a (really simple) patch for this : 

`from setuptools.command.develop import develop`

seems to do the trick

**Comment by arthurlogilab** [comment]
is it the same as ``pip install -e ./pepper`` ?

**Comment by whiteinge** [comment]
I'm not familiar with `python setup develop`. I do use `pip install -e` when I develop. We're trying to avoid using setuptools, is the pip route sufficient or is there an equivalent in distutils?
