### ISSUE TITLE
PyPI version is wrong

### ISSUE THREAD

**Issue by kottenator** [saltstack/pepper#42]
On PyPI, there is `salt-pepper==0.3.5` (only)
When I do `pip install salt-pepper`, it fetches `salt-pepper-0.3.5.tar.gz` and installs it.
But then I do `pip freeze | gerp pepper` and it shows `salt-pepper==0.0.0`
Also, could you keep all previous versions on PyPI and not delete them?

**Comment by whiteinge** [comment]
I can reproduce this. Do you know where pip fetches that version information from? It [should be available in the metadata](https://github.com/saltstack/pepper/blob/e1b959214358f033be385ef55787d18e7c8966d1/setup.py#L125) but it looks like I missed something.

I don't delete old releases off PyPI. Try editing the URL: Example:

https://pypi.python.org/pypi?name=salt-pepper&version=0.2.0&:action=display

**Comment by kottenator** [comment]
Yes, now I see that all versions are presented, excuse me

**Comment by kottenator** [comment]
However, installed version is still `0.0.0` :) 
Sorry, I can't quickly find the reason of the bug

**Comment by whiteinge** [comment]
It's likely a minor fix...once we find it. :-)

**Comment by EugeniuZ** [comment]
I believe this is the source of the bug: https://github.com/saltstack/pepper/blob/master/setup.py#L47
git_dir is empty after this call and as a result version and sha are None.

**Comment by whiteinge** [comment]
Oh, good catch! You're right. If there's no Git directory we should look for the JSON file instead. <facepalm>

If you care to send a pull req with the fix, I will push a new version to PyPI.

**Comment by EugeniuZ** [comment]
https://github.com/saltstack/pepper/pull/61

**Comment by whiteinge** [comment]
Thanks for the fix! [Release 0.4.0](https://github.com/saltstack/pepper/releases/tag/0.4.0) is now cut and uploaded to PyPI.

**Comment by EugeniuZ** [comment]
You're welcome. Thanks for uploading it so fast.
