### ISSUE TITLE
New Release for pypi

### ISSUE THREAD

**Issue by TheScriptSage** [saltstack/pepper#49]
Hey folks,

Can we cut a new release?  I want to get all the nice changes that have been implemented.

Thanks!

**Comment by sixninetynine** [comment]
+1 :)

**Comment by whiteinge** [comment]
Pushed!

https://github.com/saltstack/pepper/releases/tag/0.3.7

**Comment by sixninetynine** [comment]
you da man! :+1:

**Comment by TheScriptSage** [comment]
Thanks!
