### ISSUE TITLE
RunnerClient name=value parsing does not work as intended

### ISSUE THREAD

**Issue by whiteinge** [saltstack/pepper#57]
Bug identified in #55 by @jfroche.

The problem can be clearly seen via the following command. In addition to the `name=value` parsing, the arguments in RunnerClient are not being run through the YAML parser like in `LocalClient`.

```
pepper --client=runner test.arg foo bar=Bar baz=true qux='{qux: Qux, quux: false}'
```

**Comment by whiteinge** [comment]
This appears to be a deficiency in `RunnerClient.cmd_sync()` and `RunnerClient.cmd_async()` which are the methods that salt-api calls. `RunnerClient.cmd()` works correctly which is what the `salt-run` CLI command uses.

```python
>>> import salt.config
>>> import salt.runner
>>> opts = salt.config.master_config('/etc/salt/master')
>>> runner = salt.runner.RunnerClient(opts)
>>> runner.cmd('test.arg', ['foo', 'bar=Bar', 'baz=True'])
{'args': ('foo',), 'kwargs': {'bar': 'Bar', 'baz': True}}
>>> runner.cmd_sync({'fun': 'test.arg', 'arg': ['foo', 'bar=Bar', 'baz=True'], 'username': 'saltdev', 'password': 'saltdev', 'eauth': 'auto'})
{'args': [], 'kwargs': {'arg': ['foo', 'bar=Bar', 'baz=True']}}
```

It looks like the two methods above are [not processing the input through salt.utils.args.parse_input()](https://github.com/saltstack/salt/blob/bdea243/salt/runner.py#L143-L156) which both `LocalClient` and `RunnerClient.cmd()` use.

@jfroche does this bug sound like something you can tackle from here? My available Salt time is limited at the moment. If not we can tag the core Salt team on the issue and they can add it to their sprint backlog.

**Comment by whiteinge** [comment]
Er. That shell session may not be 100% accurate. Pepper may be sending slightly differently low data when using `--client=runner`. Must verify what Pepper is sending first, but `parse_input()` is still the likely fix.

**Comment by Ashald** [comment]
+1

**Comment by Ashald** [comment]
So the PR with the fix is merged into Salt's `develop` branch. Let's wait for its release. ;)

**Comment by whiteinge** [comment]
@Ashald thank you very much for fixing that!
