### ISSUE TITLE
Async call to `salt-run` (orchestration)

### ISSUE THREAD

**Issue by PierreR** [saltstack/pepper#58]
How do I make an async call to `salt-run` (orchestration) ? I just want to wait for the jid. I have tried both `no-interactive` and `--fail-if-incomplete` but without success.

**Comment by whiteinge** [comment]
You want the `client` flag.

```
pepper --client=runner_async <mod.func>
```

**Comment by PierreR** [comment]
Thanks for your quick help ! I knew about `local_async` but didn't assume it would work with `runner_async`.

**Comment by whiteinge** [comment]
Reasonable non-assumption. We need better docs on that...
