### ISSUE TITLE
0.5.0 Planning

### ISSUE THREAD

**Issue by theherk** [saltstack/pepper#67]
Do you plan to release 0.5.0 following the recent changes? If not, I'll just release the latest HEAD to my PyShop. That be pretty neat if you did though.

**Comment by whiteinge** [comment]
The only thing standing in the way of cutting a new release is testing
SSL _without cert validation_ on Python 2.6 and 2.5. If someone is
able to do a quick smoke-test there I would be appreciative. Otherwise
I won't be able to take a look myself until at least the weekend.

**Comment by danielfrg** [comment]
I have been using SSL without cert validation on python2.7 with no issues and just tested a little bit on 2.6 and worked for me.

**Comment by whiteinge** [comment]
@danielfrg thank you! I'll cut a release.

**Comment by whiteinge** [comment]
0.4.1 is cut:

https://pypi.python.org/pypi/salt-pepper/0.4.1
https://github.com/saltstack/pepper/releases/tag/0.4.1

**Comment by kottenator** [comment]
Hi!

When do you plan to release `0.5.0` version? I really need Python 3 support ...

**Comment by whiteinge** [comment]
@kottenator very sorry that we missed your query here! 0.5.0 is now cut.

https://github.com/saltstack/pepper/releases/tag/0.5.0
