### ISSUE TITLE
Use pepper on a windows machine

### ISSUE THREAD

**Issue by jensgustafsson** [saltstack/pepper#73]
It is not possible to use pepper as a console script on windows. In order to run the CLI you must write python path/to/script/pepper.

**Comment by whiteinge** [comment]
Hi, @jensgustafsson. Apologies for the slow reply!

I don't know how to invoke a Python script on Windows (or how to dual-purpose the same script on both Windows and Linux) but that would be a great addition. Any suggestions welcome.
