### ISSUE TITLE
PIP version

### ISSUE THREAD

**Issue by jmelchiori** [saltstack/pepper#79]
Any chance on pushing a new version to pip?  Currently it's broken for python 3.3 installs at least as some of the code in init was not python3 friendly.  I can get into specifics if you want.

**Comment by whiteinge** [comment]
Apologies for no response here! A new team at SaltStack has adopted this repo so we should have faster responses in the future. Release 0.5.0 is now available. Please file issues if you encounter any Python 3 trouble.

https://github.com/saltstack/pepper/releases/tag/0.5.0
